Fix up some issue in batlife with {1.5,175,11.3.1,12.1.0}

diff --git a/olpc-pwr-common b/olpc-pwr-common
--- a/olpc-pwr-common
+++ b/olpc-pwr-common
@@ -12,15 +12,17 @@ function pwrlog_module_init
 	    if [[ -e $x/mfg-data ]]; then OFW=$x; break; fi
 	done
 
-	ec_cmds=/sys/power/ec
-	if [[ ! -e $ec_cmds ]]; then
-	    	ec_cmds=/sys/kernel/debug/olpc-ec/generic
-		if [[ ! -e $ec_cmds ]]; then
-		    sudo mount -t debugfs none /sys/kernel/debug
-		    if [[ ! -e $ec_cmds ]]; then
-			echo "Missing kernel support for embedded controller commands"
-		    fi
-		fi
+        sudo mount -t debugfs none /sys/kernel/debug
+	ec_cmds=
+	for x in /sys/kernel/debug/olpc-ec/{cmd,generic} /sys/power/ec; do
+	    if [[ -e $x ]]; then
+		ec_cmds=$x
+		break
+	    fi
+	done
+	if [[ -z $ec_cmds ]]; then
+	    echo "COVERAGE: missing kernel support for embedded controller commands (#10933)"
+	    exit 3
 	fi
 
 	if [ -e /usr/share/olpc-utils/olpc-utils-functions ]; then
@@ -111,7 +113,7 @@ function ec_set_wakup_mask()
 	if [[ $XO_VERSION = "1" ]]; then
 		return
 	elif [[ $XO_VERSION = "1.5" ]]; then
-		printf "1b:0 b9 \n"  > $ec_cmds
+		printf "1b:0 b9 \n"  | sudo tee -a $ec_cmds > /dev/null
 	elif [[ $XO_VERSION = "1.75" ]]; then
 		printf "38:0 60 00 \n" > $ec_cmds
 	fi
@@ -128,10 +130,10 @@ function ec_get_Vin()
 	if [[ $XO_VERSION = "1" ]]; then
 		echo "0"
 		return
+	elif [[ $XO_VERSION = "1.5" ]]; then
+		printf "42:1 \n" | sudo tee -a $ec_cmds > /dev/null
 	elif [[ $XO_VERSION = "1.75" ]]; then
 		printf "5c:2 \n" > $ec_cmds
-	else
-		printf "42:1 \n" > $ec_cmds 
 	fi
 	printf "%s %s" $(< $ec_cmds )
 }
@@ -397,9 +399,12 @@ function set_backlight_full()
 	set_backlight 15 
 }
 
-function format_hundreds_as_n.nn 
+function format_hundreds_as_n.nn
 {
     local INTV=$(( ${1} / 100 ))
-    local FRACV=$(( ${1} - ( ${INTV}*100 ) ))
+    local FRACV=$(( ${1} % 100 ))
+    if [ ${FRACV} -lt 0 ]; then
+	let "FRACV = $(( 0 - ${FRACV} ))"
+    fi
     printf "%d.%02d" ${INTV} ${FRACV}
 }
