Fix wlan problems when suspending
Previous code did not set a wakeup so the interface was getting its
power turned off.  Thus it had to re-DHCP an address.

diff --git a/olpc-batlife b/olpc-batlife
--- a/olpc-batlife
+++ b/olpc-batlife
@@ -89,6 +89,19 @@ function video_test()
 	killall -r 'gst-launch*' > /dev/null
 }
 
+# This will snap a battery reading and then updated the screen with status
+# you must have initialized the pwr log system first.
+function do_reading_with_stat()
+{
+    take_reading
+    log_reading
+    VOLT_100s=$(( ${VOLT}/10000 ))
+    VOLT_INT=$(( ${VOLT_100s}/100 ))
+    VOLT_FRAC=$(( ${VOLT_100s} - ( ${VOLT_INT}*100 ) ))
+    WATTS_100s=$(( $W_SAMPLE/10 ))
+    WATTS_STR=$(format_hundreds_as_n.nn $WATTS_100s)
+    printf "SOC: %d %%, Runtime: %d minutes, Net mAh: %d , Watts: %s W\n"  $CAPLEVEL $NET_MINUTES $MAh_NET $WATTS_STR
+}
 
 pwrlog_module_init
 
@@ -130,11 +143,9 @@ fi
 
 # Next we do a loop of fetching a 1MiB file from dev.laptop.org and then a suspend
 # until powerd shuts us down.
-LOOP_TIME=60
-# Adding this delay didn't help. On 1.5 there are occurrances of > 60 seconds where 
-# there's not an association afer resume.
-SUSPEND_DELAY=0
-LOOP_BASE=$(( ${LOOP_TIME} - ${SUSPEND_DELAY} ))
+
+INTFACE_DELAY=1
+LOOP_BASE=120
 DOWNLOAD_SECONDS=$(( (${LOOP_BASE}*${WEB_DUTY_CYCLE}*100)/10000 ))
 SUSPEND_SECONDS=$(( ${LOOP_BASE}-${DOWNLOAD_SECONDS} ))
 
@@ -148,33 +159,32 @@ do
     i=0
     while [ $(diff_time ${TSTART}) -lt ${DOWNLOAD_SECONDS} ]
     do
-	curl -Ss -m 10 http://dev.laptop.org/~rsmith/batlife.dat > /dev/null
+	DL_SPEED=`curl -w "%{speed_download}" -Ss -m 10 http://dev.laptop.org/~rsmith/batlife.dat -o /dev/null`
 	CURL_RET=$?
 	if [ $? -eq 0 ]; then
-		printf "Fetch count: $i                \r" >&2
+		printf "Fetch count: $i Speed: $DL_SPEED \r" >&2
 	else
-		printf "Curl error: $CURL_RET count $i \r" >&2
+		printf "\nCurl error: $CURL_RET count $i                 \r" >&2
 	fi
 	i=$(( $i+1 ))
     done
     echo
+    do_reading_with_stat
+
     TSTART=$(get_timestamp)
     i=0
     while [ $(diff_time ${TSTART}) -lt ${SUSPEND_SECONDS} ]
     do
 	printf "Sus loop: $i   \r" >&2
+	# We have to set a wakeup source or the wlan will lose power in suspend
+	sudo ethtool -s eth0 wol u
 	sudo rtcwake --seconds 10 --mode mem > /dev/null 2>/dev/null
 	i=$(( $i+1 ))
+	# It takes some time for the interface to show back up after a resume
+	sleep $INTFACE_DELAY
     done
     echo
-    take_reading
-    log_reading
-    VOLT_100s=$(( ${VOLT}/10000 ))
-    VOLT_INT=$(( ${VOLT_100s}/100 ))
-    VOLT_FRAC=$(( ${VOLT_100s} - ( ${VOLT_INT}*100 ) ))
-    WATTS_100s=$(( $W_SAMPLE/10 ))
-    WATTS_STR=$(format_hundreds_as_n.nn $WATTS_100s)
-    printf "SOC: %d %%, Runtime: %d minutes, Net mAh: %d , Watts: %s W\n"  $CAPLEVEL $NET_MINUTES $MAh_NET $WATTS_STR
+    do_reading_with_stat
 done
 
 echo -n "$PRGNAME ending at "
